### ISSUE TITLE
How to represent SELECT EXISTS and the like 

### ISSUE THREAD

**Issue by mudrz** [roddyyaga/ppx_rapper#14]
hey @roddyyaga 
I tried to write some simple Postgres queries, but can't figure out how I'm supposed to represent these:
```ocaml
  type regclass_response = { to_regclass : string option }
  let get_something = [%rapper get_opt {sql| SELECT to_regclass(my_table_name) |sql} record_out]
```
```
|| Fatal error: exception Error in ppx_rapper: 'record_out' should not be set when there are no output parameters
```
So I guess I'm supposed to somehow include `@string?{to_regclass}` in the query, but in practice the SELECT doesn't include such slot like `SELECT @string?{to_regclass} FROM table`

It's the same with:
```sql
SELECT EXISTS (
  SELECT 1
  FROM pg_tables
  WHERE schemaname = 'schema_name' AND tablename = 'table_name'
);
```
what should the `record_out` for `SELECT EXISTS` be and how it should be represented?

**Comment by roddyyaga** [comment]
The way ppx_rapper works is that any input parameter `%type{whatever}` turns into the SQL parameter `?` in the query passed to Caqti, and any output parameter `@type{whatever}` is simply replaced with `whatever` (the only point of output parameters is so we know how to process the data returned by executing the query). So you can put output parameters anywhere in the query as long as they contain the record field/similar you want to get out.

So for your first example, this should work:
```ocaml
  type regclass_response = { to_regclass : string option }
  let get_something = [%rapper get_opt {sql| SELECT @string?{to_regclass}(my_table_name) |sql} record_out]
```

For both your examples, I would personally not use `record_out` since there is only one output field. In that case you could put `@bool{}` anywhere, around `EXISTS` seems logical to me. Or if you wanted a record with an `exists` field, you could use `record_out`, make `EXISTS` lowercase and use that as the parameter. In general, you can also put comments in the query, specifying parameters with any names.
